### ISSUE TITLE
naming suggestion

### ISSUE THREAD

**Issue by zernonia** [cpreston321/h3-defu#1]
This `h3-defu` definitely will come in handy!

But I think changing the name of `getBodyWithDefaults` to `useBodyWithDefaults` (similar to default `useBody`) will be easier to recognize and remember by developers.

What do you think?

**Comment by cpreston321** [comment]
@zernonia Funny enough I was going to do that but it looks like they are deprecating that function. 

https://github.com/unjs/h3/blob/f6ceb5581043dc4d8b6eab91e9be4531e0c30f8e/src/utils/body.ts#L74-L75

So I went with the same convention.

**Comment by cpreston321** [comment]
I could possibly do that and deprecate them until everyone is familiar with the convention!

**Comment by cpreston321** [comment]
Done 💯  It's not recommend but it's there.
